packaging_format = 2

id = "shaarli"
name = "Shaarli"
description.en = "Save, sort, synchronize and share web addresses"
description.fr = "Sauvegarder, trier, synchroniser et partager des adresses web"

version = "0.14.0~ynh1"

maintainers = ["Lapineige"]

[upstream]
license = "MIT"
demo = "https://demo.shaarli.org/"
admindoc = "https://shaarli.readthedocs.io/en/master/"
code = "https://github.com/shaarli/Shaarli"

[integration]
yunohost = ">= 11.2.30"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/shaarli"

    [install.init_main_permission]
    help.en = "If set as 'visitors', Shaarli will be visible to anyone, including non-YunoHost users. However only Shaarli users can add bookmarks. Your links will be public by default, but you can change that in Shaarli's configuration page."
    help.fr = "Si configuré en 'visiteurs', Shaarli sera visible par tout le monde, y compris des personnes sans compte sur votre YunoHost. Cependant seules les personnes avec un compte Shaarli pourrons ajouter des marques-pages. Vos nouveaux liens seront publics par défaut, mais vous pourrez changer ça dans la page de configuration de Shaarli."
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

    [install.title]
    ask.en = "Choose a title for your Shaarli instance"
    ask.fr = "Choisissez un titre pour votre instance Shaarli"
    type = "string"
    example = "Shaarli"
    default = "Shaarli"

[resources]
        [resources.sources.main]
        url = "https://github.com/shaarli/Shaarli/releases/download/v0.14.0/shaarli-v0.14.0-full.tar.gz"
        sha256 = "bd34a362b75ee8e0d09c887bed49b831c47d33c28a5a7b88191184ed208c642d"
        autoupdate.strategy = "latest_github_release"
        autoupdate.asset = "shaarli-v\\d+(\\.\\d+)+-full\\.tar\\.gz"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"
    api.url = "/api"
    api.allowed = "visitors"
    api.auth_header = false
    api.show_tile = false
    api.protected = true

    [resources.apt]
    packages = "php8.2-cli, php8.2-gettext, php8.2-curl, php8.2-intl, php8.2-gd, php8.2-mbstring, php8.2-simplexml, php8.2-ldap"
