#sub_path_only rewrite ^__PATH__$ __PATH__/ permanent;
location __PATH__/ {

  # Path to source
  alias __INSTALL_DIR__/;

  index index.php;

  if (!-f $request_filename) {
    rewrite ^ __PATH__/index.php last;
  }
  
  client_max_body_size 50M;
  try_files $uri $uri/ index.php$is_args$args;

  location ~ [^/]\.php(/|$) {
    fastcgi_pass unix:/var/run/php/php__PHP_VERSION__-fpm-__APP__.sock;
    include fastcgi_params_no_auth;
  }
}
